### ISSUE TITLE
Reading SPI with TransferFullDuplex method does not deliver any data on Raspberry PI 2

### ISSUE THREAD

**Issue by Norbert62** [ms-iot/BusProviders#19] opened 2015-12-29 13:17 UTC
The following code delivers only empty bytes in resultBuffer. deviceCmd is a SPI device on line 0 using the lightning provider:

```
    public ushort ReadCmd(byte address)
    {
        byte[] readCmd = { 0x3, address, 0, 0 };
        byte[] resultBuffer = new byte[4];

        this.deviceCmd.TransferFullDuplex(readCmd, resultBuffer);
        ushort result = (ushort)(resultBuffer[3] + (resultBuffer[2] << 8));

        return result;
    }
```

The test device is a vlsi codec chip. The same method run with the Inbox driver delivers data as expected. Platform is Raspberry Pi 2 Model B running Windows IoT 10.0.10586. Method TransferSequential does not work either with lightning provider.

**Comment by MahmoudGSaleh** [comment] 2016-02-19 23:33
Thanks for finding this issue! 
Can you please provide more context into the issue? 
As self-contained source code, as well as details about the device used would be very helpful.

Thanks!

**Comment by Norbert62** [comment] 2016-02-20 23:50
The bug was detected using a vlsi 1503 codec chip. Trying to read a value from a command register using full duplex SPI transfers failed with the lightning code. It works flawlessly with the builtin spi driver.

**Comment by IoTGirl** [comment] 2017-03-20 23:54
Closing after review by @msalehmsft - Unable to reproduce this issue.

**Closed as completed by IoTGirl** 2017-03-20 23:54 UTC

**Comment by chaholl** [comment] 2017-04-06 14:03
I've experienced the same issue. The problem can be replicated by following this hackster project and enabling Lightning drivers: https://www.hackster.io/dotMorten/windowsiottouch-44af19

Some further investigation revealed that the problem occurs when more than one thread is accessing the SPI device at the same time. For some reason the old driver was more tolerant of that behaviour but the lightning driver isn't. I suspect there's some underlying timing differences that cause the new behaviour.
